# See http://about.travis-ci.org/docs/user/build-configuration/

language: scala

scala:
  - 2.11.6
  - 2.11.7
  - 2.11.8
  - 2.11.11
  - 2.12.0
  - 2.12.1
  - 2.12.2
  - 2.12.3
  - 2.12.4

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.11.6
      jdk: oraclejdk7
    - scala: 2.11.7
      jdk: openjdk7
    - scala: 2.11.8
      jdk: oraclejdk7
    - scala: 2.11.11
      jdk: openjdk7
